use_frameworks!

target "remotegarage" do
  pod 'Firebase', '~> 3.4.0'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Messaging'
  pod 'GoogleSignIn'
  #pod 'Firebase/RemoteConfig'
  #pod 'Firebase/Storage'
  #pod 'FBSDKCoreKit'
  #pod 'FBSDKLoginKit'
end
